# Generated by Django 6.0.3 on 2026-03-11 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guruh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Guruh nomi')),
                ('rang', models.CharField(default='#00c6ff', max_length=7, verbose_name='Rang (hex)')),
                ('ikonka', models.CharField(default='🎓', max_length=10, verbose_name='Ikonka')),
                ('tartib', models.IntegerField(default=0, verbose_name='Tartib')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
                'ordering': ['tartib', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Dars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(verbose_name='Sana')),
                ('hafta_kuni', models.CharField(max_length=20, verbose_name='Hafta kuni')),
                ('para', models.CharField(blank=True, max_length=10, verbose_name='Para')),
                ('vaqt', models.CharField(blank=True, max_length=20, verbose_name='Vaqt')),
                ('modul', models.TextField(verbose_name='Modul nomi')),
                ('tur', models.CharField(blank=True, max_length=50, verbose_name='Dars turi')),
                ('oqituvchi', models.CharField(blank=True, max_length=200, verbose_name="O'qituvchi")),
                ('xona', models.CharField(blank=True, max_length=50, verbose_name='Xona')),
                ('guruh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='darslar', to='jadval.guruh')),
            ],
            options={
                'verbose_name': 'Dars',
                'verbose_name_plural': 'Darslar',
                'ordering': ['sana', 'para'],
            },
        ),
    ]
