# Generated by Django 6.0.3 on 2026-03-12 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jadval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guruh',
            name='ikonka_rasm',
            field=models.ImageField(blank=True, null=True, upload_to='ikonkalar/', verbose_name='Ikonka rasmi (ixtiyoriy)'),
        ),
    ]
